const ActionType = {
  APP_REQUEST_GET_USER: "APP_REQUEST_GET_USER",
  APP_REQUEST_GET_RIGS: "APP_REQUEST_GET_RIGS",
  APP_REQUEST_GET_CONFIG: "APP_REQUEST_GET_CONFIG",
  APP_REQUEST_PUT_USER: "APP_REQUEST_PUT_USER",
  APP_REQUEST_PUT_RIGS: "APP_REQUEST_PUT_RIGS",
  COPY_DATA_RIG: "COPY_DATA_RIG",
  COPY_DATA_USER: "COPY_DATA_USER",
  COPY_DATA_TEMP: "COPY_DATA_TEMP",
  COPY_DATA_INFO: "COPY_DATA_INFO",
  APP_REQUEST_PUT_ARR: "APP_REQUEST_PUT_ARR",
  APP_REQUEWRITE_DATA_TEMPST_PUT_ARR: "WRITE_DATA_TEMP",
  APP_REQUEST_PUT_MAIL: "APP_REQUEST_PUT_MAIL",
  APP_REQUEST_GET_INFO: "APP_REQUEST_GET_INFO",
}

export default ActionType;